
import { test, expect } from '@playwright/test';

test.describe('Work Order Creation Flow', () => {

    test('Create Work Order (Happy Path)', async ({ page }) => {
        // 1. Login
        await page.goto('/auth/login');
        await page.fill('input[type="email"]', 'demo@demo.com');
        await page.fill('input[type="password"]', 'password');
        await page.click('button:has-text("Sign In")');
        await page.waitForURL(/\/dashboard/);

        // 2. Navigate to Wizard
        await page.goto('/dashboard/work-orders/new');
        await expect(page).toHaveURL(/\/work-orders\/new/);

        // 3. Step 1: Select Asset
        // Wait for asset tree to load (assuming Headquarters is there from Seed)
        await expect(page.getByText('Headquarters')).toBeVisible({ timeout: 30000 });

        // Expand/Select logic might vary based on UI implementation
        // For now, assume expanding the tree or selecting the root.
        // If clicking expanding:
        // await page.click('text=Headquarters'); 
        // For 'Select' button if present. Assuming AssetTree has a selection mechanism.
        // Let's assume we click the node "Headquarters" which makes it "Selected", then click Next.

        // Click the node text to select it (AssetNode usually handles click)
        await page.click('text=Headquarters');

        // Click Next
        await page.click('button:has-text("Next")');

        // 4. Step 2: Details & RIME
        await expect(page.getByText('Work Order Details')).toBeVisible();

        const testTitle = `E2E Test Order ${Date.now()}`;
        await page.fill('input[name="title"]', testTitle);
        await page.fill('textarea[name="description"]', 'Generated by Playwright');

        // Select Priority
        // Assuming Select component or native select.
        // If ShadCN Select:
        await page.click('button[role="combobox"]'); // Open Valid Trigger... might track label?
        // Let's try native or role based interaction for typical Select
        // Wait, if it's ShadCN select, need to click trigger then option.
        // Inspecting wizard code would be ideal, but here is a robust guess for 'Priority'

        // Try filling mandatory fields first.
        // If RIME is auto-calculated on priority change, let's change priority.
        // Default might be 'LOW'.

        // Find Priority Select trigger. Labels usually associate.
        // Or simpler: just use default priority (LOW) and verify score > 0.
        // Let's verify RIME badge exists.
        await expect(page.locator('.bg-green-100, .bg-yellow-100, .bg-orange-100, .bg-red-100')).toBeVisible();
        // Or specific RIME score text
        // await expect(page.getByText(/Score:/)).toBeVisible();

        // Click Create
        await page.click('button:has-text("Create Work Order")');

        // 5. Success & Redirect
        // Should go to /dashboard/work-orders (or /dashboard)
        await page.waitForURL(/\/dashboard\/work-orders/);

        // 6. Verify New Item in List
        // Wait for list reload
        await expect(page.getByText(testTitle)).toBeVisible({ timeout: 30000 });
    });
});
